apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: address-service 
  namespace: 2048-game
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: address-service
    spec:
      containers:
      - name: address-service
        image: 224605180493.dkr.ecr.us-east-1.amazonaws.com/address-service:v1
        ports:
        - containerPort: 80
